#!/usr/bin/env python3
"""Emit a reviewable SQL script that dedupes per-device tables and adds
PRIMARY KEY (timestamp) on each.

Runs ONLY read-only queries against the DB (LIST tables, COUNT dupes).
Writes a `.sql` file next to itself with one transaction per dirty table.

Usage:
    python3 migrations/dedupe_per_device.py [--out FILE] [--apply]

Default mode is dry-run + emit SQL file. Pass `--apply` to ALSO execute the
generated statements -- each table in its own transaction with a progress
print. Operator confirmation required if `--apply` is passed.

Recommended workflow:
    1. Take a DB backup.
    2. Run without `--apply` -- review the emitted .sql file.
    3. Execute selectively with psql, or re-run with `--apply` for all.
    4. After all dirty tables are dedupe'd, re-run `apply.py` so migration
       006 picks up where it left off and re-attempts PK addition.
"""
import argparse
import datetime
import os
import sys

import psycopg2
from dotenv import load_dotenv


load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), os.pardir, ".env"))


def get_dirty_tables(cur):
    """Return list of (table_name, row_count, duplicate_group_count) for
    per-device tables with duplicate timestamps."""
    cur.execute(
        """
        SELECT table_name FROM information_schema.tables
        WHERE table_schema='public'
          AND table_name ~ '^(apollo_air_1|apollo_msr_2|athom_smart_plug_v2|airgradient_one|sensibo|zigbee2mqtt)_'
        ORDER BY table_name;
        """
    )
    candidates = [r[0] for r in cur.fetchall()]
    dirty = []
    for t in candidates:
        try:
            cur.execute(f"SELECT count(*) FROM public.{t}")
            n = cur.fetchone()[0]
            if n == 0:
                continue
            cur.execute(
                f"SELECT count(*) FROM (SELECT timestamp FROM public.{t} GROUP BY timestamp HAVING count(*) > 1) d;"
            )
            dups = cur.fetchone()[0]
            if dups > 0:
                dirty.append((t, n, dups))
        except Exception as err:
            print(f"  WARN: probe failed for {t}: {err}", file=sys.stderr)
            cur.connection.rollback()
    return dirty


SQL_TEMPLATE = """-- {table}: rows={rows} duplicate_groups={dups}
BEGIN;
    -- Delete duplicate rows, keeping one per timestamp (lowest ctid).
    DELETE FROM public.{table} a
    USING public.{table} b
    WHERE a.ctid < b.ctid
      AND a.timestamp = b.timestamp;

    -- Add the primary key now that duplicates are gone.
    ALTER TABLE public.{table} ADD PRIMARY KEY (timestamp);
COMMIT;
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=None,
                    help="Output SQL file path. Default: ./dedupe_<timestamp>.sql next to this script.")
    ap.add_argument("--apply", action="store_true",
                    help="EXECUTE the dedupe + PK addition for each dirty table. "
                         "Requires the operator to type the confirmation phrase.")
    args = ap.parse_args()

    if args.out is None:
        ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        # Write outside `migrations/` so apply.py doesn't pick it up next run.
        args.out = os.path.normpath(os.path.join(os.path.dirname(__file__), os.pardir, f"dedupe_{ts}.sql"))

    conn = psycopg2.connect(
        host=os.environ["DATABASE_IP"], dbname=os.environ["DATABASE_NAME"],
        user=os.environ["DATABASE_USERNAME"], password=os.environ["DATABASE_PASSWORD"],
        port=os.environ["DATABASE_PORT"], connect_timeout=10,
    )
    conn.autocommit = True  # read-only queries; not modifying anything yet
    cur = conn.cursor()

    print("Scanning per-device tables for duplicate timestamps...")
    dirty = get_dirty_tables(cur)
    print(f"Found {len(dirty)} dirty table(s).")

    if not dirty:
        print("Nothing to do. All per-device tables are dedup-able as-is.")
        conn.close()
        return

    header = (
        "-- Auto-generated by migrations/dedupe_per_device.py\n"
        f"-- Generated: {datetime.datetime.now().isoformat()}\n"
        f"-- Source DB: {os.environ['DATABASE_IP']}:{os.environ['DATABASE_PORT']}/{os.environ['DATABASE_NAME']}\n"
        f"-- Tables to dedupe: {len(dirty)}\n"
        "--\n"
        "-- Review before running. Apply with:\n"
        "--     psql -h <host> -U <user> -d <db> -f <this file>\n"
        "-- Or selectively per table.\n"
        "--\n"
        "-- Each transaction is isolated; failure on one table does not stop the next.\n\n"
    )
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write(header)
        for table, rows, dups in dirty:
            fh.write(SQL_TEMPLATE.format(table=table, rows=rows, dups=dups))
            fh.write("\n")
    print(f"Wrote SQL to: {args.out}")

    if not args.apply:
        print("\nDry-run only. Review the .sql file, then either:")
        print(f"  psql -h {os.environ['DATABASE_IP']} -U {os.environ['DATABASE_USERNAME']} -d {os.environ['DATABASE_NAME']} -f {args.out}")
        print("or re-run this script with --apply.")
        conn.close()
        return

    # Apply mode: confirm.
    print(f"\nABOUT TO MODIFY {len(dirty)} TABLE(S) IN PRODUCTION.")
    print("Type exactly: DEDUPE AND ADD PK")
    typed = sys.stdin.readline().rstrip("\n")
    if typed != "DEDUPE AND ADD PK":
        print("Aborted.")
        conn.close()
        sys.exit(2)

    ok = 0
    skipped = 0
    for table, rows, dups in dirty:
        try:
            print(f"  {table}: dedupe ({rows} rows, {dups} dup groups)...", end=" ", flush=True)
            cur.execute(f"BEGIN")
            cur.execute(f"DELETE FROM public.{table} a USING public.{table} b WHERE a.ctid < b.ctid AND a.timestamp = b.timestamp")
            deleted = cur.rowcount
            cur.execute(f"ALTER TABLE public.{table} ADD PRIMARY KEY (timestamp)")
            cur.execute("COMMIT")
            print(f"deleted={deleted} PK added")
            ok += 1
        except Exception as err:
            cur.execute("ROLLBACK")
            print(f"SKIPPED ({err})")
            skipped += 1

    print(f"\nDone. {ok}/{len(dirty)} tables processed; {skipped} skipped.")
    conn.close()


if __name__ == "__main__":
    main()
